name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que estés utilizando para desplegar tu sitio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (si usas Node.js)
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Cambia esto a la versión que necesites

      - name: Install dependencies
        run: npm install  # O 'npm ci' si prefieres

      - name: Build the project
        run: npm run build  # Asegúrate de que este comando genera tu página estática

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Usa el token que GitHub proporciona automáticamente
          publish_dir: ./dist  # Cambia esto si tu carpeta de salida es diferente (por ejemplo, 'build')
